services:
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=todouser
      - POSTGRES_PASSWORD=todopassword
      - POSTGRES_DB=todolist
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: python:3.11-alpine
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://todouser:todopassword@db:5432/todolist
      DEBUG: 1
    volumes:
      - ./server:/app
    working_dir: /app
    ports:
      - "8000:8000"
    command: >
      sh -c "
        apk add --no-cache postgresql-dev gcc &&
        pip install --no-cache-dir -r requirements.txt &&
        python manage.py runserver 0.0.0.0:8000
      "

  frontend:
    image: node:20-alpine3.18
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:8000/api
    volumes:
      - ./client:/app
      - /app/node_modules

    working_dir: /app
    ports:
      - "3000:3000"
    command: >
      sh -c "
        npm ci &&
        npm run dev
      "

volumes:
  postgres_data: